# Generated by Django 2.2.7 on 2019-11-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('SecondName', models.CharField(max_length=255)),
                ('Registration', models.CharField(max_length=255)),
                ('Hostel', models.BooleanField(default=False)),
                ('LaptopSerialNumber', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Student',
            },
        ),
    ]
