# Generated by Django 2.2.6 on 2019-11-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20191107_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LaptopSerialNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
