# Generated by Django 2.2.6 on 2019-11-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20191108_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LaptopSerialNumber',
            field=models.CharField(blank=True, default='No laptop', max_length=255, null=True),
        ),
    ]
