# Generated by Django 2.2.7 on 2019-11-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20191108_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LaptopSerialNumber',
            field=models.CharField(blank=True, default='No laptop', max_length=255),
        ),
    ]
